defaults: &defaults
  :log_level: warn
  :redis:
    :host: localhost
    :port: 6380

:development:
  <<: *defaults
  :log_level: debug

:test:
  <<: *defaults
  :redis:
    :host: localhost
    :port: 6379
    :db: 15

:production:
  <<: *defaults
